[project]
name = "foodlog"
version = "0.1.0"
description = "Track food purchases, nutrition, and consumption with SQLite"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.poetry.group.test.dependencies]
pytest = [
    {version = ">=7.0.0", python = "==3.10"},
	{version = ">=7.0.0", python = "==3.11"},
	{version = ">=7.0.0", python = "==3.12"},
	{version = ">=7.0.0", python = "==3.13"},
    {version = ">=8.0.0", python = "==3.14"}
]
pytest-cov = "*"
pytest-html = "*"
